---
displayName: Java Maven-JDK8
description: Java Stack with OpenJDK 8 and Maven 3.6.0
tags: ["Java", "OpenJDK", "Maven", "Debian"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2674Mi

