---
displayName: Go Real World Application
description: Go Stack with Go 1.12.9 and real wold application
tags: ["Debian", "Go"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
